max_width = 79
#chain_width = 0
#fn_single_line = true
#format_strings = true
#hex_literal_case = "Lower"
imports_layout = "Vertical"
#match_arm_leading_pipes = "Always"
#match_block_trailing_comma = true
imports_granularity = "Crate"
normalize_comments = true
#normalize_doc_attributes = true
#overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
tab_spaces = 2
#trailing_comma = "Always"
#use_field_init_shorthand = true
#wrap_comments = true
