on: [push]

name: Test

env:
  CARGO_TERM_COLOR: always
  PATH: "${{ runner.temp }}/llvm/bin:$PATH"
  LDFLAGS: "-L${{ runner.temp }}/llvm/lib -Wl,-rpath,${{ runner.temp }}/llvm/lib"

jobs:
  test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.0"
          directory: ${{ runner.temp }}/llvm
      - uses: actions/setup-python@v3
      - name: Run linters and check
        uses: pre-commit/action@v3.0.0
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
